import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "@/utils/api";
import { MainNav } from "../components/MainNav";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-secondary">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <Link href="/admin/dashboard">Dashboard</Link>
        </div>
      </main>
    </>
  );
};

export default Home;
